src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="orders")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $carrierName;

    /**
     * @ORM\Column(type="float")
     */
    private $deliveryPrice;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $delivery;

    /**
     * @ORM\OneToMany(targetEntity=OrderDetail::class, mappedBy="myOrder")
     */
    private $orderDetails;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isPaid;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $reference;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $stripeSessionId;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $shippingNumber;

    public function __construct()
    {
        $this->orderDetails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClient(): ?User
    {
        return $this->client;
    }

    public function setClient(?User $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCarrierName(): ?string
    {
        return $this->carrierName;
    }

    public function setCarrierName(string $carrierName): self
    {
        $this->carrierName = $carrierName;

        return $this;
    }

    public function getDeliveryPrice(): ?float
    {
        return $this->deliveryPrice;
    }

    public function setDeliveryPrice(float $deliveryPrice): self
    {
        $this->deliveryPrice = $deliveryPrice;

        return $this;
    }

    public function getDelivery(): ?string
    {
        return $this->delivery;
    }

    public function setDelivery(string $delivery): self
    {
        $this->delivery = $delivery;

        return $this;
    }

    /**
     * @return Collection<int, OrderDetail>
     */
    public function getOrderDetails(): Collection
    {
        return $this->orderDetails;
    }

    public function addOrderDetail(OrderDetail $orderDetail): self
    {
        if (!$this->orderDetails->contains($orderDetail)) {
            $this->orderDetails[] = $orderDetail;
            $orderDetail->setMyOrder($this);
        }

        return $this;
    }

    public function removeOrderDetail(OrderDetail $orderDetail): self
    {
        if ($this->orderDetails->removeElement($orderDetail)) {
            // set the owning side to null (unless already changed)
            if ($orderDetail->getMyOrder() === $this) {
                $orderDetail->setMyOrder(null);
            }
        }

        return $this;
    }

    public function isIsPaid(): ?bool
    {
        return $this->isPaid;
    }

    public function setIsPaid(bool $isPaid): self
    {
        $this->isPaid = $isPaid;

        return $this;
    }

    public function getTotal()
    {
        $total = 0;
        foreach ($this->getOrderDetails()->getValues() as $product) {
            $total += $product->getTotal();
        }
        return $total;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getStripeSessionId(): ?string
    {
        return $this->stripeSessionId;
    }

    public function setStripeSessionId(?string $stripeSessionId): self
    {
        $this->stripeSessionId = $stripeSessionId;

        return $this;
    }

    public function getShippingNumber(): ?string
    {
        return $this->shippingNumber;
    }

    public function setShippingNumber(?string $shippingNumber): self
    {
        $this->shippingNumber = $shippingNumber;

        return $this;
    }
}

src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 */
class Produit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $subtitle;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="produits")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isBest;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getSubtitle(): ?string
    {
        return $this->subtitle;
    }

    public function setSubtitle(string $subtitle): self
    {
        $this->subtitle = $subtitle;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function isIsBest(): ?bool
    {
        return $this->isBest;
    }

    public function setIsBest(bool $isBest): self
    {
        $this->isBest = $isBest;

        return $this;
    }
}

src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\Adress;
use App\Entity\Carrier;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $user = $options["user"];
        $builder
            ->add('delivery', EntityType::class, [
                "label" => false,
                "required" => true,
                "class" => Adress::class,
                "multiple" => false,
                "expanded" => true,
                "choices" => $user->getAdresses()
            ])
            ->add('carriers', EntityType::class, [
                "label" => "Choisir mon adresse de transporteur",
                "required" => true,
                "class" => Carrier::class,
                "multiple" => false,
                "expanded" => true,
            ])
            ->add("submit", SubmitType::class, [
                "label" => "Valider mon panier",
                "attr" => [
                    "class" => "btn btn-primary btn-block"
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            "user" => array()
        ]);
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;


use App\Classe\Cart;
use App\Entity\User;
use App\Entity\Order;
use DateTimeImmutable;
use App\Form\OrderType;
use App\Entity\OrderDetail;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class OrderController extends AbstractController
{

    private $entityManager;

    public function __construct(ManagerRegistry $doctrine)
    {
        $this->entityManager = $doctrine->getManager();
    }

    /**
     * @Route("/commande", name="app_order")
     */
    public function index(Request $request, Cart $cart): Response
    {
        //si l'utilisateur n'a pas de panier -> redirection vers son panier vide
        if (count($cart->get()) == 0) {
            return $this->redirectToRoute("app_cart");
        }
        //si l'utilisateur n'a pas d'adresse -> redirection vers l'ajout d'adresse
        if (!$this->getUser()->getAdresses()->getValues()) {
            return $this->redirectToRoute("app_account_adress_add", ["redirection" => "panier"]);
        }

        $form = $this->createForm(OrderType::class, null, ["user" => $this->getUser()]);

        return $this->render('order/index.html.twig', [
            "form" => $form->createView(),
            "cart" => $cart->getFull()
        ]);
    }

    /**
     * @Route("/commande/recapitulatif", name="app_order_recap", methods={"POST"})
     * Ajout d'une commande en base de donnée (non payée)
     */
    public function add(Request $request, Cart $cart): Response
    {

        if (!$this->getUser()->getAdresses()->getValues()) {
            return $this->redirectToRoute("app_account_adress_add", ["redirection" => "commande"]);
        }

        $form = $this->createForm(OrderType::class, null, ["user" => $this->getUser()]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            //On met en place tout les champs dont on va avoir besoin pour Order et OrderDetail (c'est long)
            $date = new DateTimeImmutable();

            $reference = $date->format('Y-m-d') . '-' . uniqid();

            $carriers = $form->get("carriers")->getData();
            $delivery = $form->get("delivery")->getData();

            $delivery_content = $delivery->getFirstname() . ' ' . $delivery->getLastname() . " " . $delivery->getPhone();
            if ($delivery->getCompany())
                $delivery_content .= '<br>' . $delivery->getCompany();
            $delivery_content .= '<br>' . $delivery->getAdresse();
            $delivery_content .= '<br>' . $delivery->getPostal() . ' - ' . $delivery->getCity();
            $delivery_content .= '<br>' . $delivery->getCountry();

            //On créer et persist un objet Order (Commande génerale)
            $order = new Order();

            $order->setClient($this->getUser());
            $order->setCreatedAt($date);
            $order->setCarrierName($carriers->getName());
            $order->setDeliveryPrice($carriers->getPrice());
            $order->setDelivery($delivery_content);
            $order->setIsPaid(0);
            $order->setReference($reference);
            //On hardcode un numéro de suivi pour les tests
            $order->setShippingNumber("CB662173705US");

            $this->entityManager->persist($order);

            //On créer et persist des Objects orderDetail (chaque type de produit différent dans une commande)
            foreach ($cart->getFull() as $product) {
                $orderDetail = new OrderDetail();
                $orderDetail->setMyOrder($order);
                $orderDetail->setProduct($product["product"]->getName());
                $orderDetail->setQuantity($product["quantity"]);
                $orderDetail->setPrice($product["product"]->getPrice());
                $orderDetail->setTotal($product["product"]->getPrice() * $product["quantity"]);
                $this->entityManager->persist($orderDetail);
            }

            $this->entityManager->flush();

            return $this->render('order/add.html.twig', [
                "cart" => $cart->getFull(),
                "carrier" => $carriers,
                "delivery" => $delivery_content,
                "reference" => $reference
            ]);
        }

        return $this->redirectToRoute("app_cart");
    }
}

templates/order/add.html.twig
{% extends 'base.html.twig' %}

{% block titre %}Boutique - confirmer ma commande
{% endblock %}
{% block javascript %}
	<script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
	<script src="https://js.stripe.com/v3/"></script>
{% endblock %}

{% block content %}
	{% set total = null %}
	<h3>
		Je passe ma commande
	</h3>
	<p>
		Veuillez confirmer votre commande
	</p>

	<div class="row">
		<div class="col-md-6">
			<strong>
				Mon adresse :
			</strong>
			<div class="form-check">{{delivery|raw}}</div>

			<hr>
			<strong>

				Mon transporteur :

			</strong>
			<div class="form-check">
				{{ carrier.name }}
				<br>
				{{ carrier.description }}
				<br>
				{{ carrier.price|number_format(2, '.', ',')  }}
				€
			</div>
		</div>
		<div class="col-md-6">
			<div class="text-center">
				<b>Ma commande</b>
			</div>
			<div class="order-summary">
				{% for product in cart %}
					<div class="mt-2 row">
						<div class="col-2"><img src="/uploads/{{ product.product.image }}" alt="{{ product.product.name }} " class="product-cart"></div>
						<div class="col-8 my-auto">{{product.product.name}}
							<br>
							<small>x
								{{product.quantity}}</small>
						</div>
						<div class="col-2 my-auto">
							{{ ((product.product.price * product.quantity)/100)|number_format(2, '.', ',') }}
							€
						</div>
					</div>
					{% set total = total + (product.product.price * product.quantity) %}
				{% endfor %}
			</div>
			<hr>
			<strong>Sous-total :
			</strong>
			{{ ((total)/100)|number_format(2, '.', ',') }}
			€
			<br>
			<strong>Livraison :
			</strong>
			{{(carrier.price/100)|number_format(2, '.', ',')}}
			€
			<hr>
			<strong>
				Total :
			</strong>
			{{(total/100+carrier.price/100)|number_format(2, '.', ',')}}
			€

			<form action="{{path('app_stripe', {'reference' : reference})}}" method="POST">
				<button class="btn btn-block btn-primary" type="submit" id="checkout-button">
					Payer
					{{(total/100+carrier.price/100)|number_format(2, '.', ',')}}
					€</button>
			</form>
			<br>
		</div>

	</div>
{% endblock %}

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block titre %}Boutique - confirmer ma commande
{% endblock %}

{% block content %}
	<h3>
		Je passe ma commande
	</h3>
	<p>
		Veuillez confirmer votre commande
	</p>

	<div class="row">
		<div class="col-md-6">

			{% set formhtml %}
			{{ form_start(form, {action : path('app_order_recap')}) }}
			{{form_label(form.delivery, "Choisissez votre adresse :")}}
			<a href="{{path('app_account_adress_add', {'redirection': 'commande'})}}">Ajouter une adresse</a>
			{{ form_end(form) }}
			{% endset %}
			{{ formhtml|replace({ '[br]' : '<br>'})|raw }}
		</div>
		<div class="col-md-6">
			<div class="text-center">
				<b>Récapitulatif commande</b>
				<p>Retrouver ici tout les produits de votre commande</p>
			</div>
			<div class="order-summary">
				{% for product in cart %}
					<div class="mt-2 row">
						<div class="col-2"><img src="/uploads/{{ product.product.image }}" alt="{{ product.product.name }} " class="product-cart"></div>
						<div class="col-8 my-auto">{{product.product.name}}
							<br>
							<small>{{product.product.subtitle}}</small>
						</div>
						<div class="col-2 my-auto">
							x
							{{product.quantity}}
						</div>
					</div>
				{% endfor %}
			</div>
			<br>
		</div>
	</div>
{% endblock %}